import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Home() {

  const apiKey = "JAiRYKIdDYGt3tZEz9eDacoIs3qMgdq2bJWLEuP3";

  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`;

  const [data, setData] = useState();


  const getTechTransaferData = async () => {
    const response = await axios.get(url);
    const info = response.data;
    console.log(info);
    setData(info);
  }

  useEffect(() => {
    getTechTransaferData();
  }, [])



  return (
    <>
      <Head>
        <title>Can's NASA Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nasalogo.png" />
      </Head>
      <main className={styles.main}>
        <Link href='/polychromatic' className={styles.link}>View Earth</Link>
        {
          data && data.results.map((tech, index) => (
            <div className={styles.cardContainer} key={index}>
              <h1 style={{color: 'black'}}>{tech[1]}</h1>
              <Image src={tech[10]} alt={tech[1]} width={100} height={100} className={styles.techimage}/>
              <p>{tech[2]}</p>
              <p>{tech[4]}</p>
              <p>{tech[5]}</p>
            </div>
          )
          )}
                {/* {
                tech && tech.map((t, ind) => {
                    if(ind === 10) {
                      return (
                        <Image src={t} alt={t} key={ind} width={100} height={100}
                        />
                      )
                    }
                  })
                } */}
      </main>
    </>
  )
}
