import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Home() {

  const apiKey = "JAiRYKIdDYGt3tZEz9eDacoIs3qMgdq2bJWLEuP3";

  const url = `https://api.nasa.gov/planetary/apod?count=10&api_key=${apiKey}`;

  const [data, setData] = useState([]);

  const getApodData = async () => {
    try {
      const response = await axios.get(url);
      // Only keep image results
      const onlyImages = response.data.filter(item => item.media_type === "image");
      setData(onlyImages);
    } catch (error) {
      console.error("Error fetching APOD:", error);
    }
  };
  
  useEffect(() => {
    getApodData();
  }, []);



  return (
    <>
      <Head>
        <title>Can's NASA Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nasalogo.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.nav}>
          <h1>NASA APODS</h1>
          <Link href='/polychromatic' className={styles.link}>View Earth</Link>
        </div>
        <div className={styles.apodContainer}>
            {data.map((apod, index) => (
              <div key={index} className={styles.cardContainer}>
                <h2>{apod.title}</h2>

                {apod.media_type === "image" ? (
                  <Image
                    src={apod.url}
                    alt={apod.title}
                    width={400}
                    height={300}
                    className={styles.techimage}
                  />
                ) : (
                  <iframe
                    width="400"
                    height="300"
                    src={apod.url}
                    title={apod.title}
                    frameBorder="0"
                    allowFullScreen
                  ></iframe>
                )}

                <p>{apod.date}</p>
              </div>
            ))}
        </div>
      </main>
    </>
  )
}
